name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create ZIP archive
      uses: actions/archive-file@v2
      with:
        archive_format: zip
        path: public

    - name: Create Release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: test
        release_name: Release test
        draft: false
        prerelease: false
        file_output: public.zip