name: Create Zip Archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Zip public folder
      run: |
        zip -r public.zip public
        
    - name: Archive Release
      uses: actions/v2
      with:
        type: 'zip'
        filename: 'public.zip'